services:
  chat-service:
    build:
      context: ./chat-service
      dockerfile: Dockerfile

    ports:
      - "8000:8000"

    env_file:
      - ./.env

    depends_on:
      - user-service

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile

    env_file:
      - ./.env

    ports:
      - "9000:9000"